<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="NLog" Version="5.4.0" />
		<PackageReference Include="OpenCvSharp4" Version="4.10.0.20241108" />
		<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20241108" />
		<PackageReference Include="System.Drawing.Common" Version="6.0.0" />
		<PackageReference Include="Tesseract" Version="5.2.0" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="AutoHotkey.Interop">
	    <HintPath>AutoHotkey.Interop.dll</HintPath>
	  </Reference>
	</ItemGroup>
	<ItemGroup>
	  <None Update="Settings.xml">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
